name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.56.0
          cache: true
          environments: lint

      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure

  test:
    name: Test code base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.56.0
          cache: true
          environments: dev

      - name: Run tests
        run: pixi run test
